// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaulsokocacypxbqbhgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhdWxzb2tvY2FjeXB4YnFiaGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjE1ODUsImV4cCI6MjA1OTA5NzU4NX0.jodu2leU9ePJPd7iYiK8X-7SSh2OBTwLQnE_-zHOVLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);